name: Own Your Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  pull_request_review:
    types: [submitted]

concurrency:
  group: own-your-review-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: false

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: lymo-inc/own-your-review@v0.2
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
